// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ6unu6Cpg23i-JPFvxoHOJMJoKzphK6w',
    appId: '1:385670854293:web:c0b40a52e01313a2324d9c',
    messagingSenderId: '385670854293',
    projectId: 'fire-travel-8fa1e',
    authDomain: 'fire-travel-8fa1e.firebaseapp.com',
    storageBucket: 'fire-travel-8fa1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh-Y_WPUZX5dmfbETYayF6xX7ozz0WrQc',
    appId: '1:385670854293:android:499fe966c7338022324d9c',
    messagingSenderId: '385670854293',
    projectId: 'fire-travel-8fa1e',
    storageBucket: 'fire-travel-8fa1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcJLtLh0qUoqgAGG-E_BBLMVFtH_eRKc4',
    appId: '1:385670854293:ios:00bc9330c963b999324d9c',
    messagingSenderId: '385670854293',
    projectId: 'fire-travel-8fa1e',
    storageBucket: 'fire-travel-8fa1e.firebasestorage.app',
    iosBundleId: 'com.example.mytravelRw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcJLtLh0qUoqgAGG-E_BBLMVFtH_eRKc4',
    appId: '1:385670854293:ios:00bc9330c963b999324d9c',
    messagingSenderId: '385670854293',
    projectId: 'fire-travel-8fa1e',
    storageBucket: 'fire-travel-8fa1e.firebasestorage.app',
    iosBundleId: 'com.example.mytravelRw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ6unu6Cpg23i-JPFvxoHOJMJoKzphK6w',
    appId: '1:385670854293:web:125f127cef29add1324d9c',
    messagingSenderId: '385670854293',
    projectId: 'fire-travel-8fa1e',
    authDomain: 'fire-travel-8fa1e.firebaseapp.com',
    storageBucket: 'fire-travel-8fa1e.firebasestorage.app',
  );
}
